[package]
name = "zed_elixir"
version = "0.3.1"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
path = "src/elixir.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
