id = "elixir"
name = "Elixir"
description = "Elixir support."
version = "0.2.0"
schema_version = 1
authors = ["Marshall Bowers <elliott.codes@gmail.com>"]
repository = "https://github.com/zed-extensions/elixir"

[language_servers.expert]
name = "Expert"
languages = ["Elixir", "HEEX"]

[language_servers.elixir-ls]
name = "ElixirLS"
languages = ["Elixir", "HEEX"]

[language_servers.next-ls]
name = "Next LS"
languages = ["Elixir", "HEEX"]

[language_servers.lexical]
name = "Lexical"
languages = ["Elixir", "HEEX"]

[grammars.elixir]
repository = "https://github.com/elixir-lang/tree-sitter-elixir"
commit = "450a8194f5a66561135962cfc8d7545a27b61c4c"

[grammars.heex]
repository = "https://github.com/phoenixframework/tree-sitter-heex"
commit = "008626a3fad379d17c81d5ed576edd9bd7a4fbf7"
