name = "HEEx"
grammar = "heex"
path_suffixes = ["heex", "html.eex", "leex", "neex"]
autoclose_before = ">})"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = true, newline = true },
]
block_comment = ["<%!-- ", " --%>"]
tab_size = 2
scope_opt_in_language_servers = ["tailwindcss-language-server"]

[overrides.string]
completion_query_characters = ["-"]
opt_into_language_servers = ["tailwindcss-language-server"]
