name = "HEEX"
grammar = "heex"
path_suffixes = ["heex", "html.eex", "leex", "neex"]
block_comment = { start = "<%!--", prefix = "", end = "--%>", tab_size = 0 }
wrap_characters = { start_prefix = "<", start_suffix = ">", end_prefix = "</", end_suffix = ">" }
autoclose_before = ">})%"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = true, newline = true },
    { start = "%", end = "%", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "!--", end = " --", close = true, newline = false, not_in = ["string", "comment"] },
]
tab_size = 2
scope_opt_in_language_servers = ["tailwindcss-language-server"]

[overrides.string]
completion_query_characters = ["-"]
opt_into_language_servers = ["tailwindcss-language-server"]
