name = "Elixir"
grammar = "elixir"
path_suffixes = ["ex", "exs"]
line_comments = ["# "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "do", end = "end", close = false, newline = true, not_in = ["string", "comment"] },
    { start = "fn", end = "end", close = false, newline = true, not_in = ["string", "comment"] },
    { start = "<<", end = ">>", close = false, newline = true },
    { start = "\"\"\"", end = "\n\"\"\"", close = true, newline = true, not_in = ["string", "comment"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "'''", end = "\n'''", close = true, newline = true, not_in = ["string", "comment"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
tab_size = 2
scope_opt_in_language_servers = ["tailwindcss-language-server"]

[overrides.string]
word_characters = ["-"]
opt_into_language_servers = ["tailwindcss-language-server"]
